# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: Labor_SoC-Design/SoC_Project/SoC_Project.srcs/sources_1/bd/zynq_block/ip/zynq_block_processing_system7_0_0/zynq_block_processing_system7_0_0.xci
# IP: The module: 'zynq_block_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: Labor_SoC-Design/SoC_Project/SoC_Project.gen/sources_1/bd/zynq_block/ip/zynq_block_processing_system7_0_0/zynq_block_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_block_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: Labor_SoC-Design/SoC_Project/SoC_Project.srcs/sources_1/bd/zynq_block/ip/zynq_block_processing_system7_0_0/zynq_block_processing_system7_0_0.xci
# IP: The module: 'zynq_block_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: Labor_SoC-Design/SoC_Project/SoC_Project.gen/sources_1/bd/zynq_block/ip/zynq_block_processing_system7_0_0/zynq_block_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_block_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
